# Generated by Django 4.0 on 2022-01-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewEntry',
        ),
    ]
