# Generated by Django 4.0 on 2022-01-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
